from enum import Enum


class UserRole(str, Enum):
    OBSERVER = "OBSERVER"
    CASE_COORDINATOR = "CASE_COORDINATOR"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"


class CaseStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    RECEIVED = "RECEIVED"
    CLAIMED = "CLAIMED"
    UNDER_REVIEW = "UNDER_REVIEW"
    MORE_INFORMATION_NEEDED = "MORE_INFORMATION_NEEDED"
    EVIDENCE_ACCEPTED = "EVIDENCE_ACCEPTED"
    REFERRED = "REFERRED"
    NO_RESPONSIBLE_PARTNER = "NO_RESPONSIBLE_PARTNER"
    CLOSED = "CLOSED"


class CaseDecision(str, Enum):
    EVIDENCE_ACCEPTED = "EVIDENCE_ACCEPTED"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    REFER = "REFER"
    NO_FURTHER_ACTION = "NO_FURTHER_ACTION"
    NO_RESPONSIBLE_PARTNER = "NO_RESPONSIBLE_PARTNER"


class ClosureReason(str, Enum):
    RESOLVED_OR_ACTED_ON = "RESOLVED_OR_ACTED_ON"
    REFERRED_TO_ANOTHER_ORGANISATION = "REFERRED_TO_ANOTHER_ORGANISATION"
    MERGED_WITH_RELATED_INCIDENT = "MERGED_WITH_RELATED_INCIDENT"
    MONITORED_NO_ACTION_REQUIRED = "MONITORED_NO_ACTION_REQUIRED"
    NOT_SUBSTANTIATED = "NOT_SUBSTANTIATED"
    NO_RESPONSIBLE_PARTNER_AVAILABLE = "NO_RESPONSIBLE_PARTNER_AVAILABLE"
    LOGGED_FOR_REFERENCE = "LOGGED_FOR_REFERENCE"